# Generated by Django 4.1.1 on 2022-09-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('NP', 'Nomal person'), ('WP', 'Weak person')], max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
