# Generated by Django 4.1.1 on 2022-09-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_user_db_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_db',
            old_name='name',
            new_name='username',
        ),
    ]
