# Generated by Django 4.1.1 on 2022-09-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_rename_name_user_db_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busname', models.CharField(choices=[('N1', '예약버스 1번'), ('N2', '예약버스 2번'), ('N3', '예약버스 3번')], max_length=2)),
                ('startStation', models.CharField(max_length=200)),
                ('endStation', models.CharField(max_length=200)),
            ],
        ),
    ]
